import type { Job, Candidate, Interview, Requisition, Referral } from '@/types';

export const seedData: {
  jobs: Job[];
  candidates: Candidate[];
  interviews: Interview[];
  requisitions: Requisition[];
  referrals: Referral[];
} = {
  jobs: [
    {
      id: 'job-1',
      title: 'Senior Frontend Engineer',
      department: 'engineering',
      location: 'Remote',
      type: 'full_time',
      status: 'active',
      description: 'We are looking for a Senior Frontend Engineer to join our team.',
      requirements: ['5+ years React experience', 'TypeScript proficiency', 'CSS expertise'],
      salary: { min: 120000, max: 160000, currency: 'USD' },
      createdAt: '2024-01-15T10:00:00Z',
      updatedAt: '2024-01-15T10:00:00Z',
      hiringManagerId: 'user-1',
      recruiterId: 'user-2',
      applicantCount: 24,
    },
    {
      id: 'job-2',
      title: 'Product Designer',
      department: 'design',
      location: 'New York, NY',
      type: 'full_time',
      status: 'active',
      description: 'Join our design team to create beautiful user experiences.',
      requirements: ['3+ years UX/UI design', 'Figma expertise', 'User research experience'],
      salary: { min: 90000, max: 130000, currency: 'USD' },
      createdAt: '2024-01-20T10:00:00Z',
      updatedAt: '2024-01-20T10:00:00Z',
      hiringManagerId: 'user-1',
      applicantCount: 18,
    },
    {
      id: 'job-3',
      title: 'Backend Engineer',
      department: 'engineering',
      location: 'San Francisco, CA',
      type: 'full_time',
      status: 'active',
      description: 'Build scalable backend systems and APIs.',
      requirements: ['Node.js or Go', 'PostgreSQL', 'Microservices architecture'],
      salary: { min: 130000, max: 170000, currency: 'USD' },
      createdAt: '2024-02-01T10:00:00Z',
      updatedAt: '2024-02-01T10:00:00Z',
      hiringManagerId: 'user-1',
      recruiterId: 'user-2',
      applicantCount: 31,
    },
    {
      id: 'job-4',
      title: 'Marketing Manager',
      department: 'marketing',
      location: 'Austin, TX',
      type: 'full_time',
      status: 'paused',
      description: 'Lead our marketing initiatives and grow our brand.',
      requirements: ['5+ years marketing experience', 'B2B SaaS background', 'Data-driven approach'],
      salary: { min: 85000, max: 115000, currency: 'USD' },
      createdAt: '2024-02-10T10:00:00Z',
      updatedAt: '2024-02-10T10:00:00Z',
      hiringManagerId: 'user-1',
      applicantCount: 12,
    },
    {
      id: 'job-5',
      title: 'Data Analyst Intern',
      department: 'engineering',
      location: 'Remote',
      type: 'internship',
      status: 'active',
      description: 'Summer internship for data analysis.',
      requirements: ['Python or R', 'SQL basics', 'Currently enrolled in university'],
      createdAt: '2024-02-15T10:00:00Z',
      updatedAt: '2024-02-15T10:00:00Z',
      hiringManagerId: 'user-1',
      applicantCount: 45,
    },
  ],
  candidates: [
    {
      id: 'cand-1',
      name: 'Alice Johnson',
      email: 'alice@example.com',
      phone: '555-0101',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      candidateStatus: 'interview',
      stage: 'interview',
      appliedAt: '2024-02-01T10:00:00Z',
      updatedAt: '2024-02-10T10:00:00Z',
      tags: ['React', 'TypeScript'],
      rating: 4,
      notes: [],
      source: 'LinkedIn',
    },
    {
      id: 'cand-2',
      name: 'Bob Smith',
      email: 'bob@example.com',
      phone: '555-0102',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      candidateStatus: 'screening',
      stage: 'screening',
      appliedAt: '2024-02-05T10:00:00Z',
      updatedAt: '2024-02-05T10:00:00Z',
      tags: ['Vue', 'JavaScript'],
      rating: 3,
      notes: [],
      source: 'Indeed',
    },
    {
      id: 'cand-3',
      name: 'Carol White',
      email: 'carol@example.com',
      phone: '555-0103',
      jobId: 'job-2',
      jobTitle: 'Product Designer',
      candidateStatus: 'offer',
      stage: 'offer',
      appliedAt: '2024-02-08T10:00:00Z',
      updatedAt: '2024-02-20T10:00:00Z',
      tags: ['Figma', 'UX'],
      rating: 5,
      notes: [],
      source: 'Referral',
    },
    {
      id: 'cand-4',
      name: 'David Brown',
      email: 'david@example.com',
      jobId: 'job-3',
      jobTitle: 'Backend Engineer',
      candidateStatus: 'new',
      stage: 'new',
      appliedAt: '2024-02-12T10:00:00Z',
      updatedAt: '2024-02-12T10:00:00Z',
      tags: ['Node.js', 'PostgreSQL'],
      notes: [],
      source: 'Company Website',
    },
    {
      id: 'cand-5',
      name: 'Eva Martinez',
      email: 'eva@example.com',
      phone: '555-0105',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      candidateStatus: 'hired',
      stage: 'hired',
      appliedAt: '2024-01-20T10:00:00Z',
      updatedAt: '2024-02-25T10:00:00Z',
      tags: ['React', 'TypeScript', 'CSS'],
      rating: 5,
      notes: [],
      source: 'Recruiter',
    },
    {
      id: 'cand-6',
      name: 'Frank Lee',
      email: 'frank@example.com',
      jobId: 'job-3',
      jobTitle: 'Backend Engineer',
      candidateStatus: 'rejected',
      stage: 'rejected',
      appliedAt: '2024-02-03T10:00:00Z',
      updatedAt: '2024-02-15T10:00:00Z',
      tags: ['Python', 'Django'],
      rating: 2,
      notes: [],
      source: 'LinkedIn',
    },
  ],
  interviews: [
    {
      id: 'int-1',
      candidateId: 'cand-1',
      candidateName: 'Alice Johnson',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      interviewerId: 'user-3',
      interviewerName: 'Michael Chen',
      type: 'technical',
      status: 'scheduled',
      scheduledAt: '2024-03-15T14:00:00Z',
      duration: 60,
      location: 'Zoom',
    },
    {
      id: 'int-2',
      candidateId: 'cand-3',
      candidateName: 'Carol White',
      jobId: 'job-2',
      jobTitle: 'Product Designer',
      interviewerId: 'user-1',
      interviewerName: 'Sarah Johnson',
      type: 'behavioral',
      status: 'completed',
      scheduledAt: '2024-02-20T10:00:00Z',
      duration: 45,
      feedback: 'Excellent communication skills and portfolio.',
      rating: 5,
    },
    {
      id: 'int-3',
      candidateId: 'cand-2',
      candidateName: 'Bob Smith',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      interviewerId: 'user-3',
      interviewerName: 'Michael Chen',
      type: 'phone',
      status: 'scheduled',
      scheduledAt: '2024-03-18T11:00:00Z',
      duration: 30,
    },
  ],
  requisitions: [
    {
      id: 'req-1',
      title: 'Senior DevOps Engineer',
      department: 'engineering',
      requestedById: 'user-1',
      requestedByName: 'Sarah Johnson',
      status: 'approved',
      priority: 'high',
      headcount: 1,
      justification: 'Need to scale infrastructure team.',
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-15T10:00:00Z',
      approvedById: 'user-4',
      approvedByName: 'James Wilson',
    },
    {
      id: 'req-2',
      title: 'UX Researcher',
      department: 'design',
      requestedById: 'user-1',
      requestedByName: 'Sarah Johnson',
      status: 'pending',
      priority: 'medium',
      headcount: 1,
      justification: 'Need dedicated user research capability.',
      createdAt: '2024-02-01T10:00:00Z',
      updatedAt: '2024-02-01T10:00:00Z',
    },
    {
      id: 'req-3',
      title: 'Sales Development Rep (x3)',
      department: 'sales',
      requestedById: 'user-1',
      requestedByName: 'Sarah Johnson',
      status: 'draft',
      priority: 'urgent',
      headcount: 3,
      justification: 'Expanding into new markets.',
      createdAt: '2024-02-15T10:00:00Z',
      updatedAt: '2024-02-15T10:00:00Z',
    },
  ],
  referrals: [
    {
      id: 'ref-1',
      referrerId: 'user-3',
      referrerName: 'Michael Chen',
      candidateName: 'Grace Kim',
      candidateEmail: 'grace@example.com',
      jobId: 'job-1',
      jobTitle: 'Senior Frontend Engineer',
      status: 'reviewing',
      createdAt: '2024-02-10T10:00:00Z',
      notes: 'Former colleague, strong React skills.',
    },
    {
      id: 'ref-2',
      referrerId: 'user-2',
      referrerName: 'Emily Rodriguez',
      candidateName: 'Henry Davis',
      candidateEmail: 'henry@example.com',
      jobId: 'job-3',
      jobTitle: 'Backend Engineer',
      status: 'pending',
      createdAt: '2024-02-18T10:00:00Z',
    },
  ],
};
