import type { StoreState } from '@/types';

export const seedData: StoreState = {
  currentUser: {
    id: 'user-1',
    name: 'Alex Johnson',
    email: 'alex@company.com',
    role: 'admin',
  },
  jobs: [
    {
      id: 'job-1',
      title: 'Senior Frontend Engineer',
      department: 'Engineering',
      location: 'Remote',
      type: 'full_time',
      status: 'open',
      description: 'We are looking for an experienced frontend engineer to join our team.',
      requirements: '5+ years of React experience, TypeScript, CSS-in-JS',
      salary: '$120,000 - $150,000',
      closingAt: '2025-06-30',
      createdAt: '2025-01-15T10:00:00Z',
    },
    {
      id: 'job-2',
      title: 'Product Manager',
      department: 'Product',
      location: 'New York, NY',
      type: 'full_time',
      status: 'open',
      description: 'Lead product strategy and roadmap for our core platform.',
      requirements: '3+ years PM experience, data-driven mindset',
      salary: '$110,000 - $140,000',
      closingAt: '2025-07-15',
      createdAt: '2025-01-20T10:00:00Z',
    },
    {
      id: 'job-3',
      title: 'UX Designer',
      department: 'Design',
      location: 'San Francisco, CA',
      type: 'full_time',
      status: 'open',
      description: 'Create beautiful and intuitive user experiences.',
      requirements: 'Figma, user research, prototyping',
      salary: '$90,000 - $120,000',
      createdAt: '2025-02-01T10:00:00Z',
    },
    {
      id: 'job-4',
      title: 'Backend Engineer',
      department: 'Engineering',
      location: 'Remote',
      type: 'full_time',
      status: 'closed',
      description: 'Build scalable backend services.',
      requirements: 'Node.js, PostgreSQL, AWS',
      salary: '$115,000 - $145,000',
      createdAt: '2024-12-01T10:00:00Z',
    },
  ],
  candidates: [
    {
      id: 'cand-1',
      name: 'Sarah Chen',
      firstName: 'Sarah',
      lastName: 'Chen',
      email: 'sarah.chen@email.com',
      phone: '555-0101',
      status: 'interview',
      source: 'LinkedIn',
      skills: ['React', 'TypeScript', 'Node.js'],
      appliedAt: '2025-02-10T10:00:00Z',
      createdAt: '2025-02-10T10:00:00Z',
    },
    {
      id: 'cand-2',
      name: 'Marcus Williams',
      firstName: 'Marcus',
      lastName: 'Williams',
      email: 'marcus.w@email.com',
      phone: '555-0102',
      status: 'screening',
      source: 'Indeed',
      skills: ['Product Management', 'Agile', 'SQL'],
      appliedAt: '2025-02-12T10:00:00Z',
      createdAt: '2025-02-12T10:00:00Z',
    },
    {
      id: 'cand-3',
      name: 'Emily Rodriguez',
      firstName: 'Emily',
      lastName: 'Rodriguez',
      email: 'emily.r@email.com',
      phone: '555-0103',
      status: 'offer',
      source: 'Referral',
      skills: ['Figma', 'UX Research', 'Prototyping'],
      appliedAt: '2025-02-08T10:00:00Z',
      createdAt: '2025-02-08T10:00:00Z',
    },
    {
      id: 'cand-4',
      name: 'James Kim',
      firstName: 'James',
      lastName: 'Kim',
      email: 'james.kim@email.com',
      phone: '555-0104',
      status: 'new',
      source: 'direct',
      skills: ['Python', 'Django', 'PostgreSQL'],
      appliedAt: '2025-02-15T10:00:00Z',
      createdAt: '2025-02-15T10:00:00Z',
    },
    {
      id: 'cand-5',
      name: 'Priya Patel',
      firstName: 'Priya',
      lastName: 'Patel',
      email: 'priya.p@email.com',
      phone: '555-0105',
      status: 'hired',
      source: 'LinkedIn',
      skills: ['React', 'GraphQL', 'AWS'],
      appliedAt: '2025-01-20T10:00:00Z',
      createdAt: '2025-01-20T10:00:00Z',
    },
  ],
  applications: [
    {
      id: 'app-1',
      candidateId: 'cand-1',
      jobId: 'job-1',
      status: 'interview',
      appliedAt: '2025-02-10T10:00:00Z',
    },
    {
      id: 'app-2',
      candidateId: 'cand-2',
      jobId: 'job-2',
      status: 'reviewing',
      appliedAt: '2025-02-12T10:00:00Z',
    },
    {
      id: 'app-3',
      candidateId: 'cand-3',
      jobId: 'job-3',
      status: 'offer',
      appliedAt: '2025-02-08T10:00:00Z',
    },
    {
      id: 'app-4',
      candidateId: 'cand-4',
      jobId: 'job-1',
      status: 'applied',
      appliedAt: '2025-02-15T10:00:00Z',
    },
    {
      id: 'app-5',
      candidateId: 'cand-5',
      jobId: 'job-3',
      status: 'hired',
      appliedAt: '2025-01-20T10:00:00Z',
    },
  ],
  interviews: [
    {
      id: 'int-1',
      candidateId: 'cand-1',
      jobId: 'job-1',
      applicationId: 'app-1',
      interviewerId: 'user-1',
      scheduledAt: '2025-03-01T14:00:00Z',
      duration: 60,
      type: 'video',
      status: 'scheduled',
    },
    {
      id: 'int-2',
      candidateId: 'cand-3',
      jobId: 'job-3',
      applicationId: 'app-3',
      interviewerId: 'user-1',
      scheduledAt: '2025-02-20T10:00:00Z',
      duration: 45,
      type: 'video',
      status: 'completed',
      feedback: 'Excellent candidate, strong design skills.',
    },
  ],
  requisitions: [
    {
      id: 'req-1',
      title: 'Data Scientist',
      department: 'Engineering',
      requestedBy: 'Alex Johnson',
      status: 'approved',
      priority: 'high',
      createdAt: '2025-01-10T10:00:00Z',
    },
    {
      id: 'req-2',
      title: 'Marketing Manager',
      department: 'Marketing',
      requestedBy: 'Sarah Chen',
      status: 'pending',
      priority: 'medium',
      createdAt: '2025-01-25T10:00:00Z',
    },
  ],
  referrals: [
    {
      id: 'ref-1',
      referrerName: 'Priya Patel',
      referrerEmail: 'priya.p@email.com',
      candidateName: 'David Lee',
      candidateEmail: 'david.lee@email.com',
      jobId: 'job-1',
      status: 'reviewing',
      createdAt: '2025-02-18T10:00:00Z',
    },
  ],
};
