import type { StoreState } from '@/types';

export const seedData: StoreState = {
  currentUser: {
    id: 'user-1',
    name: 'Alex Johnson',
    email: 'alex@company.com',
    role: 'admin',
    department: 'HR',
  },
  users: [
    { id: 'user-1', name: 'Alex Johnson', email: 'alex@company.com', role: 'admin', department: 'HR' },
    { id: 'user-2', name: 'Sarah Miller', email: 'sarah@company.com', role: 'hiring_manager', department: 'Engineering' },
    { id: 'user-3', name: 'Tom Davis', email: 'tom@company.com', role: 'recruiter', department: 'HR' },
    { id: 'user-4', name: 'Lisa Chen', email: 'lisa@company.com', role: 'interviewer', department: 'Engineering' },
  ],
  jobs: [
    {
      id: 'job-1',
      title: 'Senior Frontend Engineer',
      department: 'Engineering',
      location: 'Remote',
      type: 'full_time',
      status: 'open',
      description: 'We are looking for a Senior Frontend Engineer to join our growing team.',
      requirements: ['5+ years React experience', 'TypeScript proficiency', 'CSS expertise'],
      postedAt: '2024-01-15T00:00:00Z',
      hiringManagerId: 'user-2',
      createdAt: '2024-01-15T00:00:00Z',
    },
    {
      id: 'job-2',
      title: 'Product Manager',
      department: 'Product',
      location: 'New York, NY',
      type: 'full_time',
      status: 'open',
      description: 'Lead product strategy and roadmap for our core platform.',
      requirements: ['3+ years PM experience', 'Strong analytical skills', 'Excellent communication'],
      postedAt: '2024-01-20T00:00:00Z',
      hiringManagerId: 'user-2',
      createdAt: '2024-01-20T00:00:00Z',
    },
    {
      id: 'job-3',
      title: 'DevOps Engineer',
      department: 'Infrastructure',
      location: 'Austin, TX',
      type: 'full_time',
      status: 'open',
      description: 'Build and maintain our cloud infrastructure.',
      requirements: ['AWS/GCP experience', 'Kubernetes', 'CI/CD pipelines'],
      postedAt: '2024-02-01T00:00:00Z',
      hiringManagerId: 'user-2',
      createdAt: '2024-02-01T00:00:00Z',
    },
  ],
  candidates: [
    {
      id: 'cand-1',
      firstName: 'Emily',
      lastName: 'Rodriguez',
      email: 'emily.r@email.com',
      phone: '+1-555-0101',
      location: 'San Francisco, CA',
      skills: ['React', 'TypeScript', 'Node.js'],
      status: 'interview',
      source: 'LinkedIn',
      createdAt: '2024-01-20T00:00:00Z',
    },
    {
      id: 'cand-2',
      firstName: 'James',
      lastName: 'Wilson',
      email: 'james.w@email.com',
      phone: '+1-555-0102',
      location: 'New York, NY',
      skills: ['Product Management', 'Agile', 'SQL'],
      status: 'screening',
      source: 'Referral',
      createdAt: '2024-01-25T00:00:00Z',
    },
    {
      id: 'cand-3',
      firstName: 'Maria',
      lastName: 'Garcia',
      email: 'maria.g@email.com',
      location: 'Austin, TX',
      skills: ['AWS', 'Kubernetes', 'Terraform'],
      status: 'offer',
      source: 'Indeed',
      createdAt: '2024-02-05T00:00:00Z',
    },
    {
      id: 'cand-4',
      firstName: 'David',
      lastName: 'Kim',
      email: 'david.k@email.com',
      skills: ['React', 'Vue', 'GraphQL'],
      status: 'new',
      source: 'Website',
      createdAt: '2024-02-10T00:00:00Z',
    },
    {
      id: 'cand-5',
      firstName: 'Sarah',
      lastName: 'Thompson',
      email: 'sarah.t@email.com',
      skills: ['Python', 'Data Analysis', 'SQL'],
      status: 'hired',
      source: 'LinkedIn',
      createdAt: '2024-01-10T00:00:00Z',
    },
  ],
  applications: [
    {
      id: 'app-1',
      jobId: 'job-1',
      candidateId: 'cand-1',
      status: 'interview',
      appliedAt: '2024-01-22T00:00:00Z',
      updatedAt: '2024-01-28T00:00:00Z',
    },
    {
      id: 'app-2',
      jobId: 'job-2',
      candidateId: 'cand-2',
      status: 'screening',
      appliedAt: '2024-01-26T00:00:00Z',
      updatedAt: '2024-01-26T00:00:00Z',
    },
    {
      id: 'app-3',
      jobId: 'job-3',
      candidateId: 'cand-3',
      status: 'offer',
      appliedAt: '2024-02-06T00:00:00Z',
      updatedAt: '2024-02-15T00:00:00Z',
    },
    {
      id: 'app-4',
      jobId: 'job-1',
      candidateId: 'cand-4',
      status: 'applied',
      appliedAt: '2024-02-11T00:00:00Z',
      updatedAt: '2024-02-11T00:00:00Z',
    },
  ],
  interviews: [
    {
      id: 'int-1',
      jobId: 'job-1',
      candidateId: 'cand-1',
      type: 'technical',
      status: 'scheduled',
      scheduledAt: '2024-02-20T10:00:00Z',
      duration: 60,
      interviewers: ['user-4'],
      createdAt: '2024-02-15T00:00:00Z',
    },
    {
      id: 'int-2',
      jobId: 'job-3',
      candidateId: 'cand-3',
      type: 'hr',
      status: 'completed',
      scheduledAt: '2024-02-10T14:00:00Z',
      duration: 45,
      interviewers: ['user-3'],
      createdAt: '2024-02-08T00:00:00Z',
    },
  ],
  requisitions: [
    {
      id: 'req-1',
      jobTitle: 'Backend Engineer',
      department: 'Engineering',
      headcount: 2,
      status: 'approved',
      priority: 'high',
      requestedBy: 'user-2',
      createdAt: '2024-01-10T00:00:00Z',
      updatedAt: '2024-01-12T00:00:00Z',
    },
    {
      id: 'req-2',
      jobTitle: 'UX Designer',
      department: 'Design',
      headcount: 1,
      status: 'pending',
      priority: 'medium',
      requestedBy: 'user-2',
      createdAt: '2024-02-01T00:00:00Z',
      updatedAt: '2024-02-01T00:00:00Z',
    },
  ],
  referrals: [
    {
      id: 'ref-1',
      referrerId: 'user-4',
      candidateName: 'Chris Anderson',
      candidateEmail: 'chris.a@email.com',
      jobId: 'job-1',
      status: 'reviewing',
      createdAt: '2024-02-05T00:00:00Z',
    },
  ],
};
